export enum Menu {
    Dashboard = 1,
    Analytics = 2,
    Certification = 3,
    Service_Associates = 4,
    Product_Associates = 5,
    Price_Management = 6,
    Service_Price = 7,
    Product_Price = 8,
    Admin = 9,
    Product_Upload = 10,
    Mass_Upload = 11,
    Add_New_Product_Segment = 12,
    Add_New_Category = 13,
    Add_New_Group = 14,
    Add_New_Product = 15,
    Service_Upload = 16,
    Add_New_Service = 17,
    Add_New_Service_Segment = 18
}